// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sllpszjitnjlgcwknoea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbHBzemppdG5qbGdjd2tub2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Njc4ODMsImV4cCI6MjA2ODU0Mzg4M30.TEaCmVkA40K_vSi0SqDbglUgHsY0UHBqMPWHFRqynlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});